background {
    monitor =
    color = rgba(0, 0, 0, 1)
}
label {
    monitor =
    text = cmd[update:10000] echo "$(date +"%H:%M")"
    color = rgba(255, 255, 255, 1)
    font_size = 120
    font_family = JetBrainsMono Nerd Font
    position = 0, 150
    halign = center
    valign = center
}
input-field {
    monitor =
    size = 300, 50
    outline_thickness = 1
    dots_center = true
    outer_color = rgba(255, 255, 255, 1)
    inner_color = rgba(0, 0, 0, 1)
    font_color = rgb(255, 255, 255)
    check_color = rgba(255, 255, 255, 1)
    fail_color = rgba(119, 119, 119, 1)
    fade_on_empty = false
    rounding = 0
    font_family = JetBrainsMono Nerd Font
    placeholder_text = <span foreground="##777777">password</span>
    position = 0, -50
    halign = center
    valign = center
}
